# Generated by Django 5.0.6 on 2026-06-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_card_alter_player_id_player_collected_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='packs',
            field=models.IntegerField(default=1),
        ),
    ]
