# Generated by Django 5.0.6 on 2026-06-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_packs'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hammers',
            field=models.IntegerField(default=5),
        ),
    ]
