# Generated by Django 5.0.6 on 2026-06-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_player_hammers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='description',
        ),
        migrations.RemoveField(
            model_name='card',
            name='name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='rarity',
        ),
    ]
