# Generated by Django 5.0.6 on 2026-06-04 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_card_description_remove_card_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='slot1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.card'),
        ),
        migrations.AddField(
            model_name='player',
            name='slot2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.card'),
        ),
        migrations.AddField(
            model_name='player',
            name='slot3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.card'),
        ),
    ]
